services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # services
    Tenolo\FormOrdered\OrderedResolvedFormTypeFactory: ~
    Tenolo\FormOrdered\Orderer\FormOrderer: ~

    Tenolo\FormOrdered\Extension\OrderedFormExtension:
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    Tenolo\FormOrdered\Extension\OrderedButtonExtension:
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ButtonType }
